### PR TITLE
fix: css generation

### PR DESCRIPTION
**Pull request by gucheen**
1. remove all css properties with 'undefined' 'null' value
2. fix font-size line-height value precision

With new logic, there's no

```css
.a {
  font-stretch: "undefined" ;
  font-kerning: null ;
  /* or */
  font-size: 5.472.0px ;
}
```

### CODE REVIEW

**Comment by mayank10j** [comment]
Good catch, 
Your fix actually does something like this in case: 

.a {
  font-stretch: "undefined" ;
  font-kerning: null ;
  /* or */
  font-size: 5.472.0px ;
}

.a {
  font-stretch:  0.0px ;
  font-kerning: 0.0px ;
  /* or */
  font-size: 5.472.0px ;
}

This causes issues as null or undefined is not equal to 0.0px 

instead it should delete whole css property and generate something like this 
.a {
  /* or */
  font-size: 5.472.0px ;
}

**Comment by gucheen** [comment]
actually，the first fixing is to remove 'undefined' and 'null'
the second fixing is change '5.472.0px' to '5.0px', since '5.472' is really meaningless in css, maybe 5.5?

**Comment by gucheen** [comment]
I forgot to seperate them in commet

**Comment by gucheen** [comment]
The result is
```css
.a {
  font-size: 5.0px;
}
```

**Comment by gucheen** [comment]
The regex remove whole line

**Comment by mayank10j** [comment]
> The regex remove whole line

In my testing it does not remove whole line in all cases, in some cases it replaces undefined and null with 0

**Comment by gucheen** [comment]
I got it, will test it later, thanks

**Pull request closed without merging**
